#!/usr/bin/env bash
svn checkout https://svn.code.sf.net/p/ctags/code/trunk /tmp/ctags
cd /tmp/ctags
wget https://gist.github.com/complex857/5693196/raw/14a770b436b5116eb22ec65492d8c0e8a4271210/0000-PHP-parser-rewrite-full-string-parameters.patch
svn patch 0000-PHP-parser-rewrite-full-string-parameters.patch
autoconf
autoheader
./configure
make
sudo make install
